import type { Metadata } from "next";
import "@/app/globals.css";
import Sidebar from "@/app/components/Sidebar";
import { CategoryProvider } from "@/app/context/CategoryContext";
import AuthGate from "../components/AuthGate";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <CategoryProvider>
      <AuthGate>
        <div className="w-full flex flex-col lg:flex-row bg-[#F4F7FD]">
          <Sidebar />
          <div className="flex-1 w-full px-10 lg:px-0 xl:px-15 2xl:px-20">
            {children}
          </div>
        </div>
      </AuthGate>
    </CategoryProvider>
  );
}
